def foo():
    try:
        pass
    except Exception as e:
        pass
